//===========================================================================
// Program ID...: Legal Practise Management System
// Author.......: Francois De Bruin Meyer
// Copyright....: BlueCrane Software Development CC
// Date.........: 21 November 2009
//---------------------------------------------------------------------------
// Description..: Select a Database for Restore purposes
//---------------------------------------------------------------------------
// Changes......:
//===========================================================================

//---------------------------------------------------------------------------
// Include statements
//---------------------------------------------------------------------------
#include <vcl.h>
#pragma hdrstop

#include "LPMS_FirstRunldSelDB.h"
#include "LPMS_FirstRunApp.h"
//---------------------------------------------------------------------------
// Autogenerated statements
//---------------------------------------------------------------------------
#pragma package(smart_init)
#pragma resource "*.dfm"

//---------------------------------------------------------------------------
//Global Definitions
//---------------------------------------------------------------------------
TFLPMS_FirstRunSelDB *FLPMS_FirstRunSelDB;

//---------------------------------------------------------------------------
// Constructor
//---------------------------------------------------------------------------
__fastcall TFLPMS_FirstRunSelDB::TFLPMS_FirstRunSelDB(TComponent* Owner)
   : TForm(Owner)
{
}

//---------------------------------------------------------------------------
// Function to make sure the user provides all required information
//---------------------------------------------------------------------------
void __fastcall TFLPMS_FirstRunSelDB::edtHostnameChange(TObject *Sender)
{
   if (edtUsername->Text.IsEmpty() || edtPassword->Text.IsEmpty() || edtHostname->Text.IsEmpty())
   {
      btnConnect->Enabled = false;
      btnConnect->Default = false;
   }
   else
   {
      btnConnect->Enabled = true;
      btnConnect->Default = true;
   }
}

//---------------------------------------------------------------------------
// User clicked on the Restore button
//---------------------------------------------------------------------------
void __fastcall TFLPMS_FirstRunSelDB::btnConnectClick(TObject *Sender)
{
   FLPMS_FirstRunApp->RestoreHost = edtHostname->Text;
   FLPMS_FirstRunApp->RestoreUser = edtUsername->Text;
   FLPMS_FirstRunApp->RestorePass = edtPassword->Text;

   FLPMS_FirstRunApp->DoRestore   = true;

   Close();
}

//---------------------------------------------------------------------------
// User clicked on the Cancel button
//---------------------------------------------------------------------------
void __fastcall TFLPMS_FirstRunSelDB::btnReturnClick(TObject *Sender)
{
   FLPMS_FirstRunApp->DoRestore = false;
   Close();
}

//---------------------------------------------------------------------------

